<a href="https://colab.research.google.com/github/KOUSHIKEYA-VADIKA/ML-Learning/blob/main/Matrix_Operations_in_Python_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Matrix addition

In [ ]:
m1=np.array([[2,3],[4,5],[5,6]])
m2=np.array([[7,3],[98,5],[5,76]])
print(m1,"\n")
print(m2,"\n")
print(m1+m2)


print(np.add(m1,m2))

[[2 3]
 [4 5]
 [5 6]] 

[[ 7  3]
 [98  5]
 [ 5 76]] 

[[  9   6]
 [102  10]
 [ 10  82]]
[[  9   6]
 [102  10]
 [ 10  82]]


Matrix subtraction

In [ ]:
m1=np.array([[2,3],[4,5],[5,6]])
m2=np.array([[7,3],[98,5],[5,76]])
print(m1,"\n")
print(m2,"\n")
print(m1-m2)

print(np.subtract(m1,m2))

[[2 3]
 [4 5]
 [5 6]] 

[[ 7  3]
 [98  5]
 [ 5 76]] 

[[ -5   0]
 [-94   0]
 [  0 -70]]
[[ -5   0]
 [-94   0]
 [  0 -70]]


matrix Multiplication with Scaler

In [ ]:
x=5
y=np.random.randint(10,size=(x,x))
print(y)
product=np.multiply(x,y)
print(product)

[[7 3 5 7 4]
 [6 5 1 6 0]
 [2 8 3 6 4]
 [6 2 2 1 8]
 [4 7 9 9 5]]
[[35 15 25 35 20]
 [30 25  5 30  0]
 [10 40 15 30 20]
 [30 10 10  5 40]
 [20 35 45 45 25]]


In [ ]:
a=np.random.randint(10,size=(3,2))
b=np.random.randint(10,size=(2,3))
print(a,"\n")

print(b)


[[7 9]
 [0 1]
 [3 3]] 

[[7 1 7]
 [0 0 1]]


In [ ]:
product=np.dot(a,b)
print(product)

[[49  7 58]
 [ 0  0  1]
 [21  3 24]]


if we use np.multipy(a,b)
it performs element wise multiplication