<a href="https://colab.research.google.com/github/KOUSHIKEYA-VADIKA/ML-Learning/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY-numerical python

Advantages of Numpy arrays :
1.allows several mathematics operations
2.Faster operations

In [ ]:
import numpy as np


List vs Numpy - time taken

In [ ]:
from time import process_time


Time taken by list

In [ ]:
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.000547063000000847


In [ ]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array=np_array+5
end_time=process_time()
print(end_time-start_time)


0.00018726100000066026


Numpy arrays


In [ ]:
l=[1,2,3,4,5]
print(l)
type(l)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

ndarray= n-dimentional *array*

In [ ]:
#creating an 1-dimensional array

a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
a.shape

(5,)

In [ ]:
b=np.array([
            (1,2,3,4)
           ,(5,6,7,8)
           ])
b.shape

(2, 4)

In [ ]:
c=np.array([(1,2,3,4),(3,4,5,6)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [3. 4. 5. 6.]]


Initial placeholders in numpy arrays

In [ ]:
#create an numpy array of zeros
x=np.zeros((4,5))
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a numpy array of 1s
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#array of a particular value
z=np.full((5,4),9)
print(z)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [ ]:
#create an identity matrix
a=np.eye(4)
print(a)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create an numpy array with random values
b=np.random.random((3,4))
print(b)

[[0.99568334 0.94246388 0.72410764 0.5711839 ]
 [0.91564088 0.10405155 0.09228527 0.45663822]
 [0.30578518 0.6176817  0.70301611 0.10319016]]


In [ ]:
#create an numpy array with random values with intergers

c=np.random.randint(10,100,(3,5))
print(c)

[[76 45 33 91 51]
 [29 12 82 29 90]
 [56 72 27 33 49]]


In [ ]:
#array of evenly spaced values
d=np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
#array of evenly spaced values ---> specifying the step

e=np.arange(10,30,2)
print(e)

[10 12 14 16 18 20 22 24 26 28]


In [ ]:
#convert a list to a numpy array
list2=[10,20,30]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30]


numpy.ndarray

can also convert tuple to numpyArray

Analysing a numpy array

In [ ]:
c=np.random.randint(10,90,(5,5))
print(c)

[[60 84 21 56 72]
 [21 63 50 25 68]
 [83 50 69 24 75]
 [55 28 68 47 76]
 [33 33 13 24 24]]


In [ ]:
#array dimension
print(c.shape)


(5, 5)


In [ ]:
#number of dimensions it has
print(c.ndim)

2


In [ ]:
#number of elements
print(c.size)

25


In [ ]:
#checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np Array


In [ ]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2) #joins two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)
print()
print(a+b)

[[7 1 1]
 [7 5 9]
 [3 6 4]]
[[11 13 10]
 [19 18 13]
 [19 10 13]]

[[18 14 11]
 [26 23 22]
 [22 16 17]]


Mathematical operations

In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[7 9 9]
 [0 7 0]
 [9 5 3]]
[[14 10 14]
 [18 16 19]
 [18 19 12]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))


[[21 19 23]
 [18 23 19]
 [27 24 15]]
[[ -7  -1  -5]
 [-18  -9 -19]
 [ -9 -14  -9]]
[[ 98  90 126]
 [  0 112   0]
 [162  95  36]]
[[0.5        0.9        0.64285714]
 [0.         0.4375     0.        ]
 [0.5        0.26315789 0.25      ]]


Array Manipulation

In [ ]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[3 0 8]
 [1 5 2]]
(2, 3)


In [ ]:
#transpose of an array

trans=np.transpose(array)
print(trans)
print(trans.shape)

[[3 1]
 [0 5]
 [8 2]]
(3, 2)


In [ ]:
trans2=array.T
print(trans2)
print(trans2.shape)

[[3 1]
 [0 5]
 [8 2]]
(3, 2)


In [ ]:
#reshaping an array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 9 8]
 [7 8 0]]
(2, 3)


In [ ]:
b=a.reshape(3,2)
print(b)

[[8 9]
 [8 7]
 [8 0]]
